steps:
   - name: gcr.io/cloud-builders/git
     args: ['fetch', '--unshallow']
     
   - name: 'gcr.io/cloud-builders/git'
     id: 'Get Version'
     entrypoint: 'bash'
     args: 
      - '-c'
      - |
        git describe --abbrev=0 --tags
        
